# -*- coding: utf-8 -*-
"""Data Types.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bJSZL5Xtn_I7OODs0rSwFpk2O74H5Myj

Python Data types

we have 3 data types in python

   - `Integer -> int -> ex: (whole numbers -> 12 | 156 | 2860 ) etc... `
   - `float -> float -> ex: (decimals -> 12.5 | 156.0 | 2860.66) etc...`
   - `string -> str -> ex : (anything in between the ' <> ' -> 'vishnu' | 'vishnu12' | '125')`
"""

12 # int

13.50 # float

'vishnu' # str

'123' # str

'data science' # str

"""##variables

If we pass data types to python | Python will check and will give the response but if I want to use it later it is not possible because we are not storing the data types in memory (temporary Memory <RAM> | or | permanent Memory <Hard disk>)

to save the data types in the Memory <temp memory> we are going to use a concept called as varibales

we can store the data type into permanent memory using varibale if we needed But defaulty the varibales will save in the data type in the Temp Memory
"""

a = 30 # save in the Memory

a # calling from Memory

a + 10

print(30)

print(56.05)

print('vishnu')

"""when you want to call a varibale from the memory please use print condition"""

print(a)

a = 30 # save in the Memory
b = 56.05 # save in the Memory
c = 'data science' # save in the Memory

print(a) # calling from Memory

print(b)

print(c)

a = 50 # save in the Memory
print(a) # calling from Memory
print(id(a)) # id checks address of varibale a and print condition is printing output

f = 53 # save in the Memory

print(f) # calling from memory

print(id(f)) # finding address of varibale f

f = 153 # save in the Memory

print(f) # calling from memory
print(id(f)) # finding address of varibale f

# Memory occupency

a = 12 # save in the Memory
b = 15.66 # save in the Memory
c = 'india' # save in the Memory
# syntax = every developer should follow the rule

"""Rules to create the Varibales

Rule no:1 -> Varibales should not start with a Number if you want to start please use underscore_

Rule no:2 -> Varibale should be either single character or single word multiple charaters with space multiple words with space is not allowed if you want please use underscore

Rule no:3 -> Python Varibales are case sensitive (capital means capital small means small )

Rule no:4 -> Dont use below Punctuations as varibale -> !"#$%&'()*+,-./:;<=>?@[\]^_{|}~`
"""

11 = 100

11a = 100

_11a = 100 # save in the Memory

print(_11a) # calling from Memory

vishnu priya = 100

p q = 10

vishnu_priya = 100

p_q = 10

name = 'vishnu'
print(NAME)

name = 'vishnu'
print(name)

$ = 10